### PR TITLE
fix: versions for objects & node version migration

### LINKED ISSUE #37: Need to increment node version
Currently on devnet we migrated the exising nodes with version 1 to version 2. But we forgot to set the version of new nodes to 2. So there are nodes currently that have the new fields but still have version 1.

Probably need to do following:

- [ ] increment version to 2 for new nodes (hardcoded value)
- [ ] write storage migration to migrate nodes with id 1 to id 2

### PR DESCRIPTION
**Pull request by DylanVerstraete**

### CODE REVIEW

File: pallet-tfgrid/src/lib.rs [hunk 1]
```diff
@@ -33,7 +33,15 @@ pub trait Config: system::Config + timestamp::Config  {
 }
 
 // Version constant that referenced the struct version
-pub const TFGRID_VERSION: u32 = 1;
+// pub const TFGRID_VERSION: u32 = 1;
```
Comment (LeeSmet) [inline pallet-tfgrid/src/lib.rs]: remove this

**Review by LeeSmet — APPROVED** [review]
